version: "2"

linters:
  default: standard
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Go Report Card linters
    - gocyclo
    - misspell
  settings:
    gocyclo:
      min-complexity: 15

formatters:
  enable:
    - gofmt # Go Report Card formatter
  settings:
    gofmt:
      simplify: true